### ISSUE TITLE
SMS and email functionality

### ISSUE THREAD

**Issue by JeremiahPinto** [noobling/Homeforenow#26]
I've looked into email and SMS functionality for our project.

For email, nodemailer is pretty good and is free. 
Here is a link to W3schools: https://www.w3schools.com/nodejs/nodejs_email.asp
And the website: https://nodemailer.com/about/
Youtube tutorial: https://www.youtube.com/watch?v=nF9g1825mwk

For SMS, nexmo is pretty reliable.
Here is a link to their website: https://www.nexmo.com/about-nexmo
And a youtube tutorial: https://www.youtube.com/watch?v=980wnspXLe0

I am currently testing out the SMS feature with the bare minimum as nexmo allows free trial

**Comment by noobling** [comment]
Yeah that will be awesome if we could implement this.
