### ISSUE TITLE
Add automatic browser reloading

### ISSUE THREAD

**Issue by noobling** [noobling/Homeforenow#30]
This would be nice feature for us, saves us from pressing refresh every time https://www.npmjs.com/package/reload

**Comment by noobling** [comment]
I looked into the package some more, it may not be appropriate for us. Might just put this feature on hold for now unless someone finds a way to implement this.

Just for you to know in future on how to implement that package @jamliii 
1. `npm install --save-dev reload`
2. `let reload = require('reload')` Put that in `app.js` under all the other requires
3.  Put `reload(app)` in `app.js` above `app.use('/', index)`
4. Go to the end of the `<body>` tag in a view file and add `script(src="/reload/reload.js")`

**Comment by jamliii** [comment]
oh boy thank you :)
